---
title: "IDENT-FAB Integrating Sphere"
output: html_document
---

```{r setup, include=FALSE,echo=FALSE}
knitr::opts_chunk$set(echo = TRUE)
require(ggplot2)
require(doParallel)
require(spectrolab)
require(stringer)
require(asdreader)
set.seed(112345)
cores=detectCores()-1
```

## Integrating Sphere Output
```{r pyranometer,echo=FALSE}
Angio=read.csv("H:/PostDoc/External_Projects/BII/Integrating Sphere/File Overview/IS_Angio.csv",head=T)

i=2

Plot=Angio$X[i]
t.rref=Angio$X.2[i]
t.rstr=Angio$X.2[i+1]
t.rtar=Angio$X.2[i+2]
m.rtar=Angio$X.2[i+3]
b.rtar=Angio$X.2[i+4]
t.rref2=Angio$X.2[i+5]
t.tref=Angio$X.5[i]
t.ttar=Angio$X.5[i+1]
m.ttar=Angio$X.5[i+2]
b.ttar=Angio$X.5[i+3]
t.tref2=Angio$X.5[i+4]
Date=Angio$X.7[i]
AngioTable=data.frame(Plot,t.rref,t.rstr,t.rtar,m.rtar,
                      b.rtar,t.rref2,t.tref,t.ttar,m.ttar,b.ttar,t.tref2,Date)
AngioTable=TableRow[0,]

while (i < 800){
  Plot=Angio$X[i]
  t.rref=Angio$X.2[i]
  t.rstr=Angio$X.2[i+1]
  t.rtar=Angio$X.2[i+2]
  m.rtar=Angio$X.2[i+3]
  b.rtar=Angio$X.2[i+4]
  t.rref2=Angio$X.2[i+5]
  t.tref=Angio$X.5[i]
  t.ttar=Angio$X.5[i+1]
  m.ttar=Angio$X.5[i+2]
  b.ttar=Angio$X.5[i+3]
  t.tref2=Angio$X.5[i+4]
  Date=Angio$X.7[i]
  i=i+6
  TableRow=data.frame(Plot,t.rref,t.rstr,t.rtar,m.rtar,
                      b.rtar,t.rref2,t.tref,t.ttar,m.ttar,b.ttar,t.tref2,Date)
  AngioTable=rbind(AngioTable,TableRow)
}

Gymno=read.csv("H:/PostDoc/External_Projects/BII/Integrating Sphere/File Overview/IS_Gymno.csv",head=T)

i=2

Plot=Gymno$X[i]
t.rref=Gymno$Scan.Number[i]
t.rstr=Gymno$Scan.Number[i+1]
t.rtar=Gymno$Scan.Number[i+2]
m.rref=Gymno$Scan.Number[i+3]
m.rstr=Gymno$Scan.Number[i+4]
m.rtar=Gymno$Scan.Number[i+5]
b.rref=Gymno$Scan.Number[i+6]
b.rstr=Gymno$Scan.Number[i+7]
b.rtar=Gymno$Scan.Number[i+8]
t.tref=Gymno$Scan.Number.1[i]
t.ttar=Gymno$Scan.Number.1[i+1]
m.tref=Gymno$Scan.Number.1[i+2]
m.ttar=Gymno$Scan.Number.1[i+3]
b.tref=Gymno$Scan.Number.1[i+4]
b.ttar=Gymno$Scan.Number.1[i+5]
Date=Gymno$X.1[i]
GymnoTable=data.frame(Plot,t.rref,t.rstr,t.rtar,m.rtar,
                      b.rtar,t.rref2,t.tref,t.ttar,m.ttar,b.ttar,t.tref2,Date)
GymnoTable=TableRow[0,]

while (i < 800){
  Plot=Gymno$X[i]
  t.rref=Gymno$Scan.Number[i]
  t.rstr=Gymno$Scan.Number[i+1]
  t.rtar=Gymno$Scan.Number[i+2]
  m.rtar=Gymno$Scan.Number[i+3]
  b.rtar=Gymno$Scan.Number[i+4]
  t.rref2=Gymno$Scan.Number[i+5]
  t.tref=Gymno$Scan.Number.1[i]
  t.ttar=Gymno$Scan.Number.1[i+1]
  m.ttar=Gymno$Scan.Number.1[i+2]
  b.ttar=Gymno$Scan.Number.1[i+3]
  t.tref2=Gymno$Scan.Number.1[i+4]
  Date=Gymno$X.1[i]
  i=i+6
  TableRow=data.frame(Plot,t.rref,t.rstr,t.rtar,m.rtar,
                      b.rtar,t.rref2,t.tref,t.ttar,m.ttar,b.ttar,t.tref2,Date)
  GymnoTable=rbind(GymnoTable,TableRow)
}

filelist=read.csv("H:/PostDoc/External_Projects/BII/ISlist.csv")

i=filelist[5,]
Date=i[,1]
TableNum=i[,2]
spectra=read_spectra(path=i[,3],format="sig",type="target_radiance")
ISTable=data.frame(Date,TableNum,spectra)
ISTable=ISTable[0,]

for (j in 1:2913)
{
  # date_time=file.info(j)$mtime
  Date=filelist[j,1]
  TableNum=filelist[j,2]
  spectra=read_spectra(path=filelist[j,3],format="sig",type="target_radiance")
  NewTable=data.frame(Date,TableNum,spectra)
  ISTable=rbind(ISTable,NewTable)
}

#Join reference table and spectra table

AngioTable
GymnoTable
ISTable

#Calculate reflectance and transmittance

i=filelist[2]
asdtime=data.frame(date_time=get_metadata(i)$when)
spectra=data.frame(get_spectra(i,type="radiance"))
blankspec=cbind(asdtime,spectra)
MainSpec=blankspec[0,]



```