---
title: "IDENT-FAB Light Analysis"
output: html_document
---

```{r setup, include=FALSE,echo=FALSE}
knitr::opts_chunk$set(echo = TRUE)
require(ggplot2)
require(doParallel)
require(spectrolab)
require(stringer)
require(asdreader)
require(tidyr)
set.seed(112345)
cores=detectCores()-1
fileloc="H:/PostDoc/External_Projects/BII/"
PSMHead=readLines(paste0(fileloc,"PSMHead.csv"))
```

## Pyranometer Output
```{r pyranometer,echo=FALSE}
pyranometer=read.csv("H:/PostDoc/External_Projects/BII/Field Data/Pyranometer/Pyranometer.csv",header=TRUE)
pyranometer$date_time=as.POSIXct(pyranometer$DateTime,format="%m/%d/%Y %H:%M:%S",tz="CET",origin=(as.POSIXct('1970-01-01')))
pyranometer$date=as.Date(pyranometer$date_time)
pyranometer$time=strftime(pyranometer$date_time, tz="CET",format="%H:%M:%S")
pyranometer=pyranometer[,c(4,5,6,2,3)]
ggplot(pyranometer,aes(x=time,y=Total))+
  geom_point()+
  facet_grid(~date)
```

## PSM Output
#### ----PSM ASCII pull still needs work----
```{r psm,echo=FALSE}

filelist=list.files(path="H:/PostDoc/External_Projects/BII/PSM",
                    pattern=paste0(".","sed","$"),
                    recursive=TRUE,
                    full.names = TRUE)

PSMtable=data.frame(matrix(0,ncol=2154,1))
colnames(PSMtable)<-PSMHead

for (j in filelist)
{
  specfile=read.csv(j,head=FALSE)
  date=specfile$V2[7]
  time=specfile$V2[8]
  date_time=paste(date,time)
  spectra=specfile$V1[30:2180]
  spectra=data.frame(spectra)
  spectra=separate(data=spectra,col=1,sep="\t",into=c("v1","v2","v3","v4"))
  spectra=spectra[,2]
  spectra=as.numeric(spectra)
  spectrat=t(spectra)
  specframe=data.frame(DateTime=date_time,Date=date,Time=time)
  spectframe=data.frame(spectrat)
  finalframe=cbind(specframe,spectframe)
  colnames(finalframe)<-PSMHead
  PSMtable=rbind(PSMtable,finalframe)
}
PSM=PSMtable

PSM$date_time=as.POSIXct(PSM$DateTime,format="%m/%d/%Y %H:%M:%S",tz="CET",origin=(as.POSIXct('1970-01-01')))
PSM$date=as.Date(PSM$date_time)
PSM$time=strftime(PSM$date_time, tz="CET",format="%H:%M:%S")
# PSM=PSM[,c(2155,2156,2157,914)]
# PSM$"1260"[PSM$"1260">20]<-NA
PSM=PSM[50]

ggplot(PSM, aes(x=as.numeric(variable), y=value, group=Replicate,color=Replicate))+
    geom_line()+
    ggtitle(paste("Sample:",f$Sample[1]))+
    ylab("value")+
    theme_bw()+
    scale_x_continuous(name="band",
                       limits=c(0, 2151),
                       breaks=seq(150, 2151,by=500),
                       labels=seq(500,2500, by=500))
```

## ASD Output
```{r asd,echo=FALSE}

filelist=list.files(path="H:/PostDoc/External_Projects/BII/ASD",
                    pattern=paste0(".","asd","$"),
                    recursive=TRUE,
                    full.names = TRUE)

i=filelist[2]
asdtime=data.frame(date_time=get_metadata(i)$when)
spectra=data.frame(get_spectra(i,type="radiance"))
blankspec=cbind(asdtime,spectra)
MainSpec=blankspec[0,]

for (j in filelist)
{
  mtime=file.info(j)$mtime
  asdtime=data.frame(date_time=get_metadata(j)$when)
  spectra=data.frame(get_spectra(j,type="radiance"))
  mergedspec=cbind(asdtime,spectra)
  MainSpec=rbind(MainSpec,mergedspec)
}
ASD=MainSpec

ASD$date_time=as.POSIXct(ASD$date_time,format="%m/%d/%Y %H:%M:%S",tz="CET",origin=(as.POSIXct('1970-01-01')))
ASD$date=as.Date(ASD$date_time)
ASD$time=strftime(ASD$date_time, tz="CET",format="%H:%M:%S")
ASDplot=ASD[,c(2153,2154,2,52,327,527)]
ASDplot=gather(ASDplot,"Wavelength","Value",3:6)

ggplot(ASDplot,aes(x=time,y=Value,color=Wavelength))+
  geom_point()+
  facet_grid(~date)
```

## SVC Output
```{r svc,echo=FALSE}

filelist=list.files(path="H:/PostDoc/External_Projects/BII/SVC",
                    pattern=paste0(".","svc","$"),
                    recursive=TRUE,
                    full.names = TRUE)

i=filelist[2]
svctime=data.frame(date_time=get_metadata(i)$when)
spectra=data.frame(get_spectra(i,type="radiance"))
blankspec=cbind(asdtime,spectra)
MainSpec=blankspec[0,]

for (j in filelist)
{
  mtime=file.info(j)$mtime
  svctime=data.frame(date_time=get_metadata(j)$when)
  spectra=data.frame(get_spectra(j,type="radiance"))
  mergedspec=cbind(asdtime,spectra)
  MainSpec=rbind(MainSpec,mergedspec)
}
ASD=MainSpec

ASD$date_time=as.POSIXct(ASD$date_time,format="%m/%d/%Y %H:%M:%S",tz="CET",origin=(as.POSIXct('1970-01-01')))
ASD$date=as.Date(ASD$date_time)
ASD$time=strftime(ASD$date_time, tz="CET",format="%H:%M:%S")
ASDplot=ASD[,c(2153,2154,2,52,327,527)]
ASDplot=gather(ASDplot,"Wavelength","Value",3:6)

ggplot(ASDplot,aes(x=time,y=Value,color=Wavelength))+
  geom_point()+
  facet_grid(~date)
```

## Merge Data by Time
```{r mdbt,echo=FALSE}

```